version: '3.8'
services:
  educativo_pg:
    image: postgres:latest
    container_name: educativo_2024
    restart: always
    environment:
      POSTGRES_DB: educativo_db
      POSTGRES_USER: userdev
      POSTGRES_PASSWORD: secret1234
    ports:
      - 5432:5432
    volumes:
      - .edu_db/dbdata:/var/lib/postgresql/data
